[project]
name = "pdf-outline-edit"
version = "26.10.1"
authors = [{ name = "slbtty", email = "shenlebantongying@gmail.com" }]
description = "Mini PDF outline editor"
readme = "README.md"
requires-python = ">=3.13"
classifiers = ["Programming Language :: Python :: 3"]

dependencies = [
    "pymupdf>= 1.28",
    "PySide6-Essentials>=6.11"
]

[project.gui-scripts]
pdf-outline-edit = "pdfoe.main:main"

[tool.uv.build-backend]
module-name = "pdfoe"
module-root = ""

[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"
